version: 2
updates:
    - package-ecosystem: "maven"
      directory: "/"
      schedule:
          interval: "weekly"
          day: "monday"
          time: "08:00"
      open-pull-requests-limit: 5
      labels:
          - "dependencies"
      commit-message:
          prefix: "chore"
          prefix-development: "test"
          include: "scope"
      assignees:
          - "rabestro"
      rebase-strategy: "auto"
